sudo: required

services:
  - docker 
    
before_install:
  - docker build -t olusegunf/react-test -f ./client/Dockerfile.dev ./client
         
script:
  - docker run -e CI=true olusegunf/react-test npm test

after_success:
  - docker build -t olusegunf/multi-client ./client
  - docker build -t olusegunf/multi-nginx ./nginx
  - docker build -t olusegunf/multi-server ./server
  - docker build -t olusegunf/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push olusegunf/multi-client
  - docker push olusegunf/multi-nginx
  - docker push olusegunf/multi-server
  - docker push olusegunf/multi-worker

deploy:
  region: us-east-2
  edge: true
  provider: elasticbeanstalk
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-360680948646
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
